# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
  - page: 首页
    url: /
    icon: fa-home
  - page: 关于我
    url: /about
    icon: fa-user
  - page: Spring Cloud
    icon: fa-fire
    subPages:
      - page: Spring Cloud
        url: /categories/SpringCloud
      - page: Spring Cloud Alibaba
        url: /categories/SpringCloudAlibaba
      # - page: Spring Boot系列教程
      #   url: /spring-boot/spring-boot-index
  - page: Spring Boot
    url: /categories/SpringBoot/
    icon: fa-heart
  - page: Python
    icon: fa-star
    subPages:
      - page: Python 基础
        url: /tags/Python-基础/
      - page: Python 爬虫
        url: /tags/Python-爬虫/
  - page: 归档
    url: /archives
    icon: fa-archive
  # - page: 系列课程
  #   icon: fa-fire
  #   subPages:
  #     - page: Docker系列教程
  #       url: /docker/00-docker-lession-index
  #     - page: Spring Cloud系列教程
  #       url: /spring-cloud/spring-cloud-index
  #     - page: Spring Boot系列教程
  #       url: /spring-boot/spring-boot-index
  # - page: 开源书
  #   icon: fa-book
  #   subPages:
  #     - page: RocketMQ开发者指南
  #       url: /books/rocketmq
  #       icon: fa-rocket
  # - page: 工具
  #   icon: fa-cog
  #   subPages:
  #     - page: 微信排版工具1.0
  #       url: /tools/markdown
  #     - page: 微信排版工具2.0
  #       url: /tools/markdown2

## favicon
favicon: /favicon.jpg

## Feed
rss: /atom.xml

## Carousel
carousel:
  img:
  url:

# 各个小工具的设置

## widgets
widgets:
  - aboutme
  - ad
  - series
  - category
  - tagcloud
  - friends
  # - notification
  # - social
  - archive

# 广告位
ad:
  # 首页侧边栏广告位
  sidebar:
    title: 腾讯云
    targetUrl: https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=93fe850c571821bb49a3529841c3a1cc&from=console
    imgUrl: /img/tengxunyun.jpg
  # 内页页头banner广告位
  innerBanner:
    - title: 腾讯云
      targetUrl: https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=93fe850c571821bb49a3529841c3a1cc&from=console
      imgUrl: /img/tengxunyuntop.jpg

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false

## 网站公告设置
#notification: |-
#            <p>
#              <b>笔者微信</b>：jumping_me，欢迎加我<br/>
#              <b>公众号</b>：请扫描我的头像<br/>
#            </p>

## 社交设置a
social:
  - name: GitHub
    icon: github
    href: //github.com/meteor1993
  - name: Gitee
    icon: git
    href: //gitee.com/inwsy
  - name: 邮箱
    icon: envelope-o
    href: mailto:inwsy@hotmail.com
  # - name: 慕课网
  #   icon: book
  #   href: //coding.imooc.com/class/358.html
  - name: RSS
    icon: feed
    href: /atom.xml

## 文章分类设置
cate_config:
  show_count: true
  show_current: true

## 文章归档设置
arch_config:
  type: 'monthly'
  format: 'YYYY年MM月'
  show_count: true
  order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#29afec'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  # - 程序猿DD|翟永超: http://blog.didispace.com/
  # - 泥瓦匠的博客: http://www.bysocket.com/
  # - 梁桂钊的博客: http://blog.720ui.com/
  # - 猿天地: http://cxytiandi.com/
  # - 二丫讲梵: http://eryajf.net/
  # - ANOYI轻量级微服务架构: https://anoyi.com
  # - python教程: https://www.yuanrenxue.com/
  # - 京东资深SRE工程师: http://www.liangsonghua.me
  # - 王欣的博客: https://wangxin.io/
  # - PM的AI知识库: https://easyai.tech/


# 主题自定义个性化配置

## 网站宣传语
branding: 分享技术，感悟人生

## 设置banner背景图片
banner:
  img:

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

  ## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme: true

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 30000
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: '本博客由极客挖掘机创作，采用
    <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank">
    CC BY 3.0 CN
    </a>
    许可协议。可自由转载、引用，但需署名作者且注明文章出处。如转载至微信公众号，请在文末添加作者公众号二维码。'

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## Valine评论
valine:
  enable: false
  appId: v4LucTmYP6UILrIu1pzb2KFG-9Nh9j0Va
  appKey: dDifHMVdvzOlU9NqKzxLAJRE
  placeholder: 说点什么吧
  notify: false
  verify: false
  avatar: mm
  meta: nick,mail
  pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
  enable: false
  clientID:
  clientSecret:
  repo:
  owner:
  admin:
  perPage:
  distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422


## 网站访客统计
visit_counter:
  site: true
  page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1277980864

### 百度统计
baidu_analytics: e0be553f264f09013e966c480c65dd5d

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics: 

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: true

#网站主题配置
since: 2019
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.0.0

# 是否开启fork me on github
fork_me_on_github:
  enabled: true
  url: http://github.com/meteor1993
